#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.scratch/glm52-local-serving/run/glm52-live-backend.env}"
MODEL_NAME="${MODEL_NAME:-zai-org/GLM-5.2}"
ADAPTER_HOST="${ADAPTER_HOST:-127.0.0.1}"
mkdir -p "$(dirname "$ENV_FILE")"

print_cmd() {
  printf '\n'
  sed 's/^/    /' <<EOF
$1
EOF
  printf '\n'
}

run_visible() {
  local command="$1"
  print_cmd "$command"
  if confirm "Run this command now?"; then
    bash -lc "$command"
  else
    note "skipped; run it manually when the prerequisite is ready"
  fi
}

require_non_empty() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$name is empty; stop and rerun after you have the value"
    exit 1
  fi
}

banner "GLM-5.2 live backend handoff"

stage "Confirm the external Chat backend"
say "This wizard does not start Dynamo, SGLang, Harbor, Docker, or Codex."
say "It captures handoff values and walks the operator through live checks."
step "Confirm the upstream is a real OpenAI-compatible Chat Completions endpoint for GLM-5.2."
step "It must serve POST /v1/chat/completions for model $MODEL_NAME."
step "Do not use SimpleHTTP, SearXNG, a static file server, or the Responses adapter URL as the upstream Chat endpoint."
warn "Observed local defaults may already be occupied: :8000 can be SimpleHTTP, :8080 can be SearXNG, and :18080 can be occupied."
if ! confirm "Do you have a real GLM-5.2 Chat Completions endpoint now?"; then
  warn "handoff stopped before any live readiness claim"
  exit 1
fi

stage "Capture endpoint values"
say "Choose free, operator-confirmed endpoints. This wizard does not probe or reserve ports."
ask GLM52_CHAT_BASE_URL "Paste GLM52_CHAT_BASE_URL, including /v1:"
require_non_empty "GLM52_CHAT_BASE_URL" "$GLM52_CHAT_BASE_URL"
write_env GLM52_CHAT_BASE_URL "$GLM52_CHAT_BASE_URL"
write_env GLM52_MODEL "$MODEL_NAME"
if confirm "Will this wizard start the local Responses adapter on a free port?"; then
  ask GLM52_RESPONSES_PORT "Paste the free GLM52_RESPONSES_PORT for the adapter:"
  require_non_empty "GLM52_RESPONSES_PORT" "$GLM52_RESPONSES_PORT"
  GLM52_RESPONSES_BASE_URL="http://$ADAPTER_HOST:$GLM52_RESPONSES_PORT/v1"
  write_env GLM52_RESPONSES_PORT "$GLM52_RESPONSES_PORT"
  write_env GLM52_RESPONSES_BASE_URL "$GLM52_RESPONSES_BASE_URL"
else
  ask GLM52_RESPONSES_BASE_URL "Paste the already-running GLM52_RESPONSES_BASE_URL, including /v1:"
  require_non_empty "GLM52_RESPONSES_BASE_URL" "$GLM52_RESPONSES_BASE_URL"
  write_env GLM52_RESPONSES_BASE_URL "$GLM52_RESPONSES_BASE_URL"
  GLM52_RESPONSES_PORT="${GLM52_RESPONSES_BASE_URL%/v1}"
  GLM52_RESPONSES_PORT="${GLM52_RESPONSES_PORT##*:}"
  if [[ ! "$GLM52_RESPONSES_PORT" =~ ^[0-9]+$ ]]; then
    ask GLM52_RESPONSES_PORT "Paste the host adapter port for Harbor routing:"
    require_non_empty "GLM52_RESPONSES_PORT" "$GLM52_RESPONSES_PORT"
  fi
  write_env GLM52_RESPONSES_PORT "$GLM52_RESPONSES_PORT"
  note "adapter port for Harbor routing: $GLM52_RESPONSES_PORT"
fi
say "Non-secret values were written to $ENV_FILE."

stage "Optional API key"
say "If the upstream endpoint requires authentication, set GLM_API_KEY."
say "The key is a secret. Commands shown later reference the variable name, not the value."
if confirm "Does this endpoint require GLM_API_KEY?"; then
  if confirm "Write GLM_API_KEY to the scratch env file?"; then
    ask_secret GLM_API_KEY "Paste GLM_API_KEY:"
    require_non_empty "GLM_API_KEY" "$GLM_API_KEY"
    write_env GLM_API_KEY "$GLM_API_KEY"
    chmod 600 "$ENV_FILE"
    say "Set file mode 600 on $ENV_FILE."
  else
    say "Export GLM_API_KEY in every shell that runs the adapter or verifier."
    pause "Press Enter after GLM_API_KEY is exported where needed."
  fi
else
  note "no GLM_API_KEY will be written"
fi

stage "Raw Chat verification"
say "This checks the upstream Chat Completions server before the adapter is involved."
say "Expected result: the response contains GLM52_HEALTH_OK."
RAW_CHAT_COMMAND=$(cat <<EOF
set -a
source '$ENV_FILE'
set +a
auth_args=()
if [[ -n "\${GLM_API_KEY:-}" ]]; then
  auth_args=(-H "Authorization: Bearer \$GLM_API_KEY")
fi
curl -sS "\$GLM52_CHAT_BASE_URL/chat/completions" \\
  -H 'Content-Type: application/json' \\
  "\${auth_args[@]}" \\
  -d '{"model":"$MODEL_NAME","messages":[{"role":"user","content":"Reply with GLM52_HEALTH_OK"}],"max_tokens":64,"chat_template_kwargs":{"enable_thinking":false}}'
EOF
)
run_visible "$RAW_CHAT_COMMAND"
say "Known failure signature: HTTP 501 from this path means the upstream is not a Chat Completions server."

stage "Start the Responses adapter"
say "The adapter exposes Codex-compatible Responses endpoints and forwards to the Chat backend."
say "The command runs inside Monarch's rootfs wrapper and is normally long-running."
if [[ -n "${GLM52_RESPONSES_PORT:-}" && "$GLM52_RESPONSES_BASE_URL" == "http://$ADAPTER_HOST:$GLM52_RESPONSES_PORT/v1" ]]; then
  ADAPTER_COMMAND="set -a; source '$ENV_FILE'; set +a; GLM52_CHAT_BASE_URL=\"\$GLM52_CHAT_BASE_URL\" scripts/run_glm52_responses_adapter.sh --host $ADAPTER_HOST --port \"\$GLM52_RESPONSES_PORT\""
  print_cmd "$ADAPTER_COMMAND"
  warn "Run this in a dedicated shell if you want the wizard to continue."
  if confirm "Run the adapter in this wizard anyway? It will occupy this terminal until stopped."; then
    bash -lc "$ADAPTER_COMMAND"
  else
    pause "Start the adapter in another shell, then press Enter."
  fi
else
  say "You provided an already-running Responses adapter URL."
  pause "Press Enter after the adapter is reachable."
fi

stage "Responses and serving verifier"
say "First check adapter model discovery, then run the full serving verifier with the terminal bench."
say "Expected adapter discovery: JSON from /v1/models advertising $MODEL_NAME."
MODELS_COMMAND="set -a; source '$ENV_FILE'; set +a; curl -sS \"\$GLM52_RESPONSES_BASE_URL/models\""
run_visible "$MODELS_COMMAND"
say "Known failure signature: SearXNG HTML on :8080 is not the adapter."
SERVING_COMMAND="set -a; source '$ENV_FILE'; set +a; GLM52_CHAT_BASE_URL=\"\$GLM52_CHAT_BASE_URL\" GLM52_RESPONSES_BASE_URL=\"\$GLM52_RESPONSES_BASE_URL\" scripts/run_glm52_serving_verifier.sh --terminal-bench"
print_cmd "$SERVING_COMMAND"
warn "The serving verifier can be long-running and writes glm52-serving-results contract artifacts."
if confirm "Run the serving verifier now?"; then
  bash -lc "$SERVING_COMMAND"
else
  note "skipped; run it manually after the adapter is stable"
fi

stage "Harbor Terminal-Bench 2 smoke"
say "Harbor's host agent uses the host-resolvable adapter URL from GLM52_RESPONSES_BASE_URL."
say "Docker tasks still use host.docker.internal through the explicit local host route."
HARBOR_COMMAND="set -a; source '$ENV_FILE'; set +a; scripts/run_glm52_benchmark_verifier.sh smoke --suite terminal-bench-2 --responses-base-url \"\$GLM52_RESPONSES_BASE_URL\" --local-host-route host.docker.internal --local-container-runtime docker --run-id \"tbench2-smoke-\$(date -u +%Y%m%dT%H%M%SZ)\""
print_cmd "$HARBOR_COMMAND"
warn "The Harbor smoke can launch containers and run benchmark tasks."
if confirm "Run the Harbor Terminal-Bench 2 smoke now?"; then
  bash -lc "$HARBOR_COMMAND"
else
  note "skipped; run it manually when Docker and Harbor are ready"
fi
say "Known failure signature: Harbor 'Responses /models preflight failed' means the adapter URL is unavailable, non-JSON, or returns an empty model list."

finish
